### ISSUE TITLE
Issues with IOF files from Winsplits Pro

### ISSUE THREAD

**Issue by dfgeorge** [LukeWoodward/SplitsBrowser#33]
Hi,

Im using Winsplits Pro to generate IOF 2.0.3 files to display using splitsbrowser (http://www.users.on.net/~dsg/splitsbrowserFile/). I have found a couple of issues:

1. Missed points dont have a time stamp (this seemt to conform to the DTD). This causes Version2Reader.readSplitTime to throw an exception. I have fixed by returning a null for time when the timestr is null, e.g. return {code: code, time: null}; inside the if test,

2. Winsplits Pro wraps the runners time in a clock tag, e.g. 
    <Time>
    <Clock clockFormat="HH:MM:SS">00:34:54</Clock>
    </Time>

This does not seem to follow the DTD :-(. This results in some new line chars being included in the time string, which breaks SplitsBrowser.parseTime. I have fixed by removing the new line chars in SplitsBrowser.parseTime, not elegant but it works and should not have any bad effects. My changes:

    SplitsBrowser.parseTime = function (timeIn) {
	var time = timeIn.replace(/(\r\n|\n|\r)/gm,"")

**Comment by LukeWoodward** [comment]
Hi again dfgeorge and thanks for your further feedback.

For point 1, I'll make SplitsBrowser assume that a control has been missed if a `<SplitTime>` element contains no `<Time>` element.  It's easy enough to do this for both IOF XML formats, i.e. v2.0.3 and v3.0, so I'll do that.

Point 2 is a nuisance.  As you say, the DTD doesn't permit a `<Clock>` element within the `<Time>` element for a competitor's total time.  Fortunately however the only knock-on effect is that we need to trim whitespace from times before we parse them.  I think the simplest thing to do there is to call `.trim()` within `SplitsBrowser.parseTime()`, as that will also pick up any other situations in other files where we need to trim whitespace.

I'm grateful to you for reporting these problems, as they help me make SplitsBrowser work better with output from WinSplits Pro.  I don't own a copy of it myself, and I hope you understand that I'm not going to spend 495 SEK on a copy of it just to test SplitsBrowser against it!

**Comment by dfgeorge** [comment]
Hi Luke,

Thanks for that. I didnt want to spend the 495 SEK either, which is why I
am using splitsbrowser :-). I am using the trial version of Winsplits Pro.
While the trial version limits most of its functionality to only a few
controls it outputs the full results in XML.

If you want to test with winsplits pro files there are a few on my site:

http://www.users.on.net/~dsg/splitsbrowserFile/data/

Thanks,

Dave

**Comment by LukeWoodward** [comment]
Thanks for your comment, Dave.  

I've now put a beta version of SplitsBrowser on the file load test page (http://www.lack-of.org.uk/dev/splitsbrowser/splitsbrowser-file-load-test.html) which fixes this issue and also contains your change as suggested in issue #34.  I've gone through all of the WinSplits Pro files on your website, and SplitsBrowser now loads all but one of them.  The one exception is day 3 of the 2014 Australian 3 Days, but I don't think I can blame SplitsBrowser for not loading that one because that file isn't well-formed XML.

I also noticed that the M21E class in day 2 of the 2014 Australian 3 Days has all competitors missing times at controls 6, 7, 9, 10, 11 and 12, but again that's not an issue with SplitsBrowser as the XML file is missing the data.

Would it be possible to give this beta version of SplitsBrowser a quick test and confirm that it working as you would expect?

Yours,

Luke

**Comment by dfgeorge** [comment]
Thanks for your effort Luke,

I have give the beta version a test and it seems to work as I expect.

As you noticed Splitsbrower Pro does not alwys produce good xml. I have had
to fix some file by hand.

Thanks again,

Dave
